// Plain-English names for the database tables shown on /admin/permissions
// ("What they can do"), grouped into areas a school leader recognises.
// A table missing from here still appears, under "Other", by its own name,
// so a new table is never hidden; add it here when you create it.

export const DATA_AREAS = [
  ['Students & families', {
    students: 'Student records (Core Data)',
    parents: 'Parent records',
    student_parent: 'Parent–child links',
    families: 'Families',
    previous_schools: 'Previous schools',
    student_documents: 'Student documents',
    sports_houses: 'Sports houses',
    boarding_houses: 'Boarding houses',
  }],
  ['Attendance', {
    attendance: 'Registers (attendance marks)',
    attendance_codes: 'Attendance codes',
    planned_absences: 'Planned absences',
    register_alerts: 'Register alerts',
    staff_attendance_records: 'Staff attendance',
  }],
  ['Behaviour', {
    behaviour_events: 'Behaviour events',
    behaviour_event_students: 'Other students in an event',
    behaviour_photos: 'Behaviour photos',
    behaviour_appeals: 'Behaviour appeals',
    behaviour_categories: 'Behaviour categories',
    behaviour_rules: 'Detention and alert rules',
    detentions: 'Detentions',
    certificate_levels: 'Certificate levels',
    certificates_awarded: 'Certificates awarded',
  }],
  ['Results & assessment', {
    results: 'Results (marks)',
    target_grades: 'Target grades',
    transcript_grades: 'Transcript grades',
    grade_history: 'Grade history (log)',
    grade_scale: 'Grade scale',
    subject_grade_boundaries: 'Grade boundaries',
    cat4_results: 'CAT4 results',
    ngrt_results: 'NGRT results',
    reading_age_tests: 'Reading age tests',
    subjects: 'Subjects',
    subject_aliases: 'Subject aliases',
    subject_key_stages: 'Subject key stages',
    departments: 'Departments',
  }],
  ['Homework', {
    homework: 'Homework set',
    homework_marks: 'Homework marks',
    homework_attachments: 'Homework files and links',
    homework_done: 'Students’ done ticks',
    homework_classes: 'Classes using homework',
    homework_schemes: 'Marking schemes',
    homework_scheme_values: 'Marking scheme values',
  }],
  ['Reports', {
    report_periods: 'Report periods',
    report_subject_comments: 'Subject comments',
    report_pastoral_comments: 'Pastoral comments',
    report_checkers: 'Report checkers',
  }],
  ['Timetable & classes', {
    classes: 'Classes',
    student_class: 'Class lists (enrolments)',
    timetable_slots: 'Timetable lessons',
    curriculum_blocks: 'Curriculum blocks',
    periods: 'Periods',
    bell_times: 'Bell times',
    mentor_groups: 'Mentor groups',
    staff_commitments: 'Staff commitments',
    terms: 'Terms',
    academic_years: 'Academic years',
    calendar_events: 'Calendar events',
  }],
  ['Next year', {
    plan_classes: 'Next year’s classes',
    plan_student_class: 'Next year’s class lists',
    plan_timetable_slots: 'Next year’s timetable',
    plan_curriculum_blocks: 'Next year’s blocks',
    plan_mentor_groups: 'Next year’s mentor groups',
    plan_mentor_assignments: 'Next year’s mentor assignments',
  }],
  ['Admissions', {
    applicants: 'Applicants',
    applicant_contacts: 'Applicant contacts',
    applicant_interviews: 'Interviews',
    applicant_letters: 'Letters sent',
    admission_test_scores: 'Test scores',
    admission_cat4: 'Admission CAT4',
    admission_sessions: 'Test days',
    admission_papers: 'Test papers',
    admission_places: 'Places allowed',
    admission_letter_templates: 'Standard letters',
  }],
  ['Fees', {
    student_invoices: 'Invoices',
    invoice_line_items: 'Invoice lines (charges)',
    fee_payments: 'Payments',
    fee_items: 'Fee items',
    fee_item_year_prices: 'Prices by year group',
    fee_price_changes: 'Price changes awaiting approval',
    fee_discount_types: 'Discount types',
    student_discounts: 'Student discounts',
    fee_terms: 'Fee terms',
    fee_charge_batches: 'Charge batches',
    fee_payment_plans: 'Payment plans',
    fee_payment_plan_installments: 'Payment plan instalments',
  }],
  ['Tuckshop', {
    tuckshop_items: 'Items and prices',
    tuckshop_purchases: 'Sales',
    tuckshop_purchase_items: 'Sale lines',
    tuckshop_preorders: 'Preorders',
    tuckshop_preorder_items: 'Preorder lines',
    tuckshop_order_schedule: 'Ordering schedule',
    tuckshop_special_sessions: 'Special sessions',
    tuckshop_special_session_items: 'Special session items',
    tuckshop_handout_saves: 'Hand-out lists',
  }],
  ['Sick bay & medical', {
    student_medical: 'Medical records',
    student_medical_conditions: 'Medical conditions',
    student_clinic_visits: 'Sick bay visits',
    student_immunisations: 'Immunisations',
    student_growth_measurements: 'Height and weight',
    student_medical_screenings: 'Screenings',
    student_screening_findings: 'Screening findings',
    bmi_for_age_reference: 'BMI reference table',
  }],
  ['The Other Half', {
    other_half_activities: 'Activities',
    other_half_activity_staff: 'Activity staff',
    other_half_choices: 'Student choices',
    other_half_terms: 'Choice windows',
  }],
  ['Student groups', {
    student_groups: 'Groups',
    student_group_members: 'Group members',
    student_group_staff: 'Group staff',
    student_group_mark_sheets: 'Group mark sheets',
    student_group_marks: 'Group marks',
  }],
  ['Staff & HR', {
    staff: 'Staff list',
    staff_hr_profiles: 'HR profiles',
    staff_training: 'Training',
    staff_warnings: 'Warnings',
  }],
  ['Messages', {
    messages: 'Messages',
    message_recipients: 'Message recipients',
    parent_welcome_sends: 'Parent welcome emails sent',
    email_reply_routes: 'Email reply addresses',
  }],
  ['Access & settings', {
    staff_roles: 'Staff roles',
    roles: 'Roles',
    role_permissions: 'Page permissions',
    resources: 'Pages list',
    student_field_permissions: 'Core Data field permissions',
    profiles: 'Logins',
    change_history: 'Change history (log)',
    dashboard_tile_order: 'Tile order',
    system_settings: 'System settings',
    system_backup_mode: 'Backup mode',
  }],
];

const LOOKUP = {};
DATA_AREAS.forEach(([area, tables]) => {
  Object.entries(tables).forEach(([table, label]) => { LOOKUP[table] = { area, label }; });
});

export function describeTable(table) {
  return LOOKUP[table] || { area: 'Other', label: table.replace(/_/g, ' ') };
}

export const AREA_ORDER = [...DATA_AREAS.map(([area]) => area), 'Other'];
