// The student Core Data fields whose Read/Edit access is set per role at
// /admin/permissions. Keys are students columns; the list must match
// student_core_fields() in migration 151, which the database enforces.
export const STUDENT_CORE_FIELDS = [
  { key: 'first_name', label: 'First name' },
  { key: 'middle_name', label: 'Middle name' },
  { key: 'last_name', label: 'Last name' },
  { key: 'preferred_name', label: 'Preferred name' },
  { key: 'legal_first_name', label: 'Legal first name' },
  { key: 'legal_last_name', label: 'Legal last name' },
  { key: 'upn', label: 'UPN' },
  { key: 'student_email', label: 'Student email' },
  { key: 'dob', label: 'Date of birth' },
  { key: 'year_group', label: 'Year group' },
  { key: 'form_class', label: 'Form' },
  { key: 'admission_date', label: 'Admission date' },
  { key: 'admitted_letter_date', label: 'Admitted/letter date' },
  { key: 'gender', label: 'Gender' },
  { key: 'nationality', label: 'Nationality' },
  { key: 'state_of_origin', label: 'State of origin' },
  { key: 'lga', label: 'LGA' },
  { key: 'home_town', label: 'Home town' },
  { key: 'religion', label: 'Religion' },
  { key: 'boarding_house', label: 'Boarding house' },
  { key: 'boarding_room_number', label: 'Boarding room number' },
  { key: 'sports_house', label: 'Sports house' },
  { key: 'restaurant', label: 'Restaurant' },
  { key: 'national_identity_number', label: 'National identity number' },
  { key: 'neco_exam_number', label: 'NECO exam number' },
  { key: 'utme_pin', label: 'UTME PIN' },
  { key: 'utme_profile_code', label: 'UTME profile code' },
  { key: 'address_line1', label: 'Address line 1' },
  { key: 'address_line2', label: 'Address line 2' },
  { key: 'city', label: 'City' },
  { key: 'postcode', label: 'Postcode' },
  { key: 'country', label: 'Country' },
  { key: 'emergency_contact_name', label: 'Emergency contact name' },
  { key: 'emergency_contact_phone', label: 'Emergency contact phone' },
  { key: 'medical_notes', label: 'Medical notes' },
  { key: 'leaving_date', label: 'Leaving date' },
  { key: 'status', label: 'Status' },
  { key: 'photo_base64', label: 'Photo' },
];
